--CREATE LOGIN ExcelReporter WITH PASSWORD = '@mxoszqNR?{59xnoxq_9uKgvmsFT7_&#$!~<Tdtklxfynyhw';
--CREATE USER ExcelReporterUser FROM LOGIN ExcelReporter;
--EXEC sp_addrolemember 'db_datareader', 'ExcelReporterUser';